# Site settings
title: Payments Remastered | Elektropay 
email: hello@elektropay.com
description: | Say goodbye to late payments and messy accounting. Find the perfect payments management tool with Elektropay. It'super easy to use and you'll love our customer service. # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://wwww.elektropay.com" # the base hostname & protocol for your site - used for feed.xml
twitter_username: elektropay
facebook_username: elektropay
linkedin_username: elektropay
github_username:  elektropay

# Build settings
markdown: kramdown
